### ISSUE TITLE
Permission selection partial: limit groups visibility

### ISSUE THREAD

**Issue by mmnosek** [Starcounter/Starcounter.Authorization#16]
I would like to discuss what groups should be presented inside permission selection partial.

**Actual behavior:**
- All groups except currently added are in results.
- All groups added to permission are presented regardless of current user's membership
- All groups added to permission are possible to delete regardless of current user membership

**Questions:**
1. What groups should be presented in search results?
2. Do all added groups should be displayed in partial?
3. Do all added group should be available to delete regardless of current user membership? 

**Expected behavior:**
TO BE FIGURED OUT.

cc @joozek78

**Comment by joozek78** [comment]
PermissionSelectionPartial has been removed
