### ISSUE TITLE
Static method of create in PermissionSelectionPartial

### ISSUE THREAD

**Issue by aloscha** [Starcounter/Starcounter.Authorization#34]
In public class we have
`public static PermissionSelectionPartial Create<TPermission>(TPermission permission)`

I think it's completely unnecessary and makes all users confused about using it. So what is the best way to create that view: call Create or create a new item and call init? What if I would like something mine into `create` I need to create a pre-create method in my project. Or if init changes I need also to change `Create`.

I think that method should be removed from that class, also never see in SC project to use static method creating new view.

**Comment by joozek78** [comment]
PermissionSelectionPartial has been removed
